package db

import (
	"context"
	"database/sql"
	"fmt"

	_ "github.com/lib/pq"

	"github.com/rohilsurana/pgfga/internal/transform"
)

func Connect(dsn string) (*sql.DB, error) {
	db, err := sql.Open("postgres", dsn)
	if err != nil {
		return nil, fmt.Errorf("connect: %w", err)
	}
	if err := db.Ping(); err != nil {
		return nil, fmt.Errorf("ping: %w", err)
	}
	return db, nil
}

func EnsureSchema(ctx context.Context, db *sql.DB) error {
	_, err := db.ExecContext(ctx, `
		CREATE TABLE IF NOT EXISTS authz_model (
			id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
			schema_version bigint NOT NULL,
			entity_type text NOT NULL,
			relation text NOT NULL,
			subject_type text,
			implied_by text,
			parent_relation text
		);
		CREATE INDEX IF NOT EXISTS schema_version_idx ON authz_model USING btree (schema_version);
		CREATE INDEX IF NOT EXISTS search_composite_idx ON authz_model USING btree (
			entity_type, relation, subject_type, implied_by, parent_relation
		);
	`)
	return err
}

func GetLatestSchemaVersion(ctx context.Context, db *sql.DB) (int64, error) {
	var version sql.NullInt64
	err := db.QueryRowContext(ctx, "SELECT max(schema_version) FROM authz_model").Scan(&version)
	if err != nil {
		return 0, err
	}
	if !version.Valid {
		return 0, nil
	}
	return version.Int64, nil
}

func DeleteSchemaVersion(ctx context.Context, tx *sql.Tx, version int64) error {
	_, err := tx.ExecContext(ctx, "DELETE FROM authz_model WHERE schema_version = $1", version)
	return err
}

func InsertAuthzModel(ctx context.Context, tx *sql.Tx, rows []transform.AuthzModelRow) error {
	stmt, err := tx.PrepareContext(ctx, `
		INSERT INTO authz_model (schema_version, entity_type, relation, subject_type, implied_by, parent_relation)
		VALUES ($1, $2, $3, $4, $5, $6)
	`)
	if err != nil {
		return err
	}
	defer stmt.Close()

	for _, row := range rows {
		_, err := stmt.ExecContext(ctx,
			row.SchemaVersion,
			row.EntityType,
			row.Relation,
			row.SubjectType,
			row.ImpliedBy,
			row.ParentRelation,
		)
		if err != nil {
			return fmt.Errorf("insert %s.%s: %w", row.EntityType, row.Relation, err)
		}
	}
	return nil
}
