create table if not exists "authz_model" (
    "id" bigint primary key generated by default as identity not null,
    "schema_version" bigint not null,
    "entity_type" text not null,
    "relation" text not null,
    "subject_type" text,
    "implied_by" text,
    "parent_relation" text
);

create index if not exists "schema_version_idx" on "authz_model" using btree ("schema_version");

create index if not exists "search_composite_idx" on "authz_model" using btree (
    "entity_type",
    "relation",
    "subject_type",
    "implied_by",
    "parent_relation"
);
